// <auto-generated />
using MaSV_NguyenVanTeo.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaSV_NguyenVanTeo.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260912031017_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.Property<int>("LopHocPhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocPhanId"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaLopHP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.HasKey("LopHocPhanId");

                    b.HasIndex("MonHocId");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Property<int>("MonHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonHocId"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTietLyThuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MonHocId");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.HasOne("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Navigation("LopHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
