// <auto-generated />
using System;
using MaSV_NguyenVanTeo.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaSV_NguyenVanTeo.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260926031640_SinhVienUnique")]
    partial class SinhVienUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.DangKyEntity", b =>
                {
                    b.Property<int>("DangKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyId"));

                    b.Property<int>("LopHocPhanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DangKyId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.Property<int>("LopHocPhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocPhanId"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaLopHP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.HasKey("LopHocPhanId");

                    b.HasIndex("MonHocId");

                    b.ToTable("LopHocPhan");

                    b.HasData(
                        new
                        {
                            LopHocPhanId = 1,
                            HocKy = 1,
                            MaLopHP = "LHP_COS101_01",
                            MonHocId = 1,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 2,
                            HocKy = 1,
                            MaLopHP = "LHP_COS101_02",
                            MonHocId = 1,
                            NamHoc = 2025,
                            SiSoToiDa = 55
                        },
                        new
                        {
                            LopHocPhanId = 3,
                            HocKy = 2,
                            MaLopHP = "LHP_COS102_01",
                            MonHocId = 2,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 4,
                            HocKy = 2,
                            MaLopHP = "LHP_COS102_02",
                            MonHocId = 2,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 5,
                            HocKy = 1,
                            MaLopHP = "LHP_COS201_01",
                            MonHocId = 3,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 6,
                            HocKy = 2,
                            MaLopHP = "LHP_COS201_02",
                            MonHocId = 3,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 7,
                            HocKy = 1,
                            MaLopHP = "LHP_COS202_01",
                            MonHocId = 4,
                            NamHoc = 2025,
                            SiSoToiDa = 65
                        },
                        new
                        {
                            LopHocPhanId = 8,
                            HocKy = 1,
                            MaLopHP = "LHP_DBS201_01",
                            MonHocId = 5,
                            NamHoc = 2025,
                            SiSoToiDa = 70
                        },
                        new
                        {
                            LopHocPhanId = 9,
                            HocKy = 2,
                            MaLopHP = "LHP_DBS201_02",
                            MonHocId = 5,
                            NamHoc = 2025,
                            SiSoToiDa = 65
                        },
                        new
                        {
                            LopHocPhanId = 10,
                            HocKy = 2,
                            MaLopHP = "LHP_DBS202_01",
                            MonHocId = 6,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 11,
                            HocKy = 1,
                            MaLopHP = "LHP_NET201_01",
                            MonHocId = 7,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 12,
                            HocKy = 2,
                            MaLopHP = "LHP_OPS201_01",
                            MonHocId = 8,
                            NamHoc = 2025,
                            SiSoToiDa = 60
                        },
                        new
                        {
                            LopHocPhanId = 13,
                            HocKy = 1,
                            MaLopHP = "LHP_WEB301_01",
                            MonHocId = 9,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 14,
                            HocKy = 1,
                            MaLopHP = "LHP_DOT301_01",
                            MonHocId = 10,
                            NamHoc = 2025,
                            SiSoToiDa = 55
                        },
                        new
                        {
                            LopHocPhanId = 15,
                            HocKy = 2,
                            MaLopHP = "LHP_DOT301_02",
                            MonHocId = 10,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        });
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Property<int>("MonHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonHocId"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTietLyThuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MonHocId");

                    b.ToTable("MonHoc");

                    b.HasData(
                        new
                        {
                            MonHocId = 1,
                            MaMon = "COS101",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Nhập môn lập trình"
                        },
                        new
                        {
                            MonHocId = 2,
                            MaMon = "COS102",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            MonHocId = 3,
                            MaMon = "COS201",
                            SoTietLyThuyet = 60,
                            SoTinChi = 4,
                            TenMon = "Cấu trúc dữ liệu và giải thuật"
                        },
                        new
                        {
                            MonHocId = 4,
                            MaMon = "COS202",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Lập trình hướng đối tượng"
                        },
                        new
                        {
                            MonHocId = 5,
                            MaMon = "DBS201",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            MonHocId = 6,
                            MaMon = "DBS202",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Hệ quản trị cơ sở dữ liệu"
                        },
                        new
                        {
                            MonHocId = 7,
                            MaMon = "NET201",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Mạng máy tính"
                        },
                        new
                        {
                            MonHocId = 8,
                            MaMon = "OPS201",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Hệ điều hành"
                        },
                        new
                        {
                            MonHocId = 9,
                            MaMon = "WEB301",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Phát triển ứng dụng Web"
                        },
                        new
                        {
                            MonHocId = 10,
                            MaMon = "DOT301",
                            SoTietLyThuyet = 45,
                            SoTinChi = 3,
                            TenMon = "Lập trình .NET nâng cao"
                        });
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.SinhVienEntity", b =>
                {
                    b.Property<int>("SinhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinhVienId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LopSinhHoat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("SinhVienId");

                    b.HasIndex("MaSV")
                        .IsUnique();

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.DangKyEntity", b =>
                {
                    b.HasOne("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", "LopHocPhan")
                        .WithMany("DangKies")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaSV_NguyenVanTeo.Api.Database.Entities.SinhVienEntity", "SinhVien")
                        .WithMany("DangKies")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.HasOne("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.Navigation("DangKies");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("MaSV_NguyenVanTeo.Api.Database.Entities.SinhVienEntity", b =>
                {
                    b.Navigation("DangKies");
                });
#pragma warning restore 612, 618
        }
    }
}
